---
 apiVersion: v1
 kind: Pod
 metadata:
   name: rss-site
   labels:
     app: web
 spec:
   containers:
     - name: front-end
       image: nginx/nginx-ingress
       ports:
         - containerPort: 80
     - name: rss-reader
       image: centos/nginx-112-centos7
       ports:
         - containerPort: 88
