apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: bitnami-nginx
    image: centos/nginx-112-centos7
    imagePullPolicy: IfNotPresent
  nodeSelector:
    disktype: ssd
