apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx/nginx-ingress
    imagePullPolicy: IfNotPresent
  nodeSelector:
    disktype: ssd
